# Site settings
name: Less Or More
email: xingmaojun@foxmail.com
author: xingmaojun
url: http://xingmaojun.github.io
resume_site: http://xingmaojun.github.io/
github: https://github.com/xingmaojun/
baseurl: "/blog"
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xingmaojun

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
#评论
commenthub_id: 3821949
